### PR TITLE
Update to latest zig

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Srekel** [comment]
Hey @data-man thanks! Are you using it by any chance, or just on a mission to ensure Zig repos are up to date? :)

**Comment by data-man** [comment]
@Srekel 
Yes, I'm using it.
But I also need a static option without an allocator.

> just on a mission to ensure Zig repos are up to date?

It's a good mission! :smile:

**Comment by Srekel** [comment]
Oh fun! May I ask what you're using it for?

**Comment by data-man** [comment]
I'm working on a Unicode module (yes, another one).
So I plan add set operations (or, and, etc.) to the zig-sparse-set.

**Pull request merged**
