### PR TITLE
Compatibility fixes for latest zig master (0.11.0-dev)

### PR DESCRIPTION
**Pull request by kcbanner**
First of all, thanks for this lib!

This is a set of changes to get this compiling and tests passing for the latest changes on zig master.

Changes:
- update build.zig
- update allocator usage
- fixup tests (adding `try`)
- add docs to gitignore and remove checked in version

### CODE REVIEW

**Comment by Srekel** [comment]
Hi, 

Wow thanks for the work! Appreciated!

Just a question, why should the docs not be in git? It's pretty nice to clone the repo and then be able to browse them in the web browser.

**Comment by kcbanner** [comment]
No problem!

The docs can definitely be in git - I just figured since they result in a > 1MB js file each time they are built, it might bloat the repo if every change rebuilds the file. That being said, things might not change that much so it may be a non-issue.

I'm happy to revert that part of the pr, whichever is preferable.

**Comment by kcbanner** [comment]
Actually I think this is a consequence of the docs including all of std (the folder structure is actually 35mb, I was accidentally looking at the old version before), I'll see if there is a way to confine it to just SparseSet.

**Comment by kcbanner** [comment]
Looks like this is not possible to exclude dependencies like std with how autodoc works currently. (see #autodoc in the zig Discord). So if checked in the folder would be approximately 35mb.

**Comment by Srekel** [comment]
Oh! Yeah in that case it's a good idea, can be added back later when the docs system is updated. :)

**Pull request merged**
